# Generated by Django 5.0.3 on 2024-07-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='usuario',
            field=models.CharField(default='', max_length=50),
        ),
    ]
